### ISSUE TITLE
Move feedback drop-down to the right

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/antora-ui-khronos#9]
Right now the feedback drop-down sits between the spec and education drop-downs, which kinda feels odd. Could we move it to the right side of Community instead?

![image](https://github.com/KhronosGroup/antora-ui-khronos/assets/10283127/5c480b41-8992-4dc2-88f1-ec34bed9e22c)

**Comment by marty-johnson59** [comment]
@SaschaWillems, Jon moved this over right before "community"  Does that work?  Closing this - but please re-open if needed
